### ISSUE TITLE
How is this package a REST client?

### ISSUE THREAD

**Issue by zedtux** [javorosas/react-native-rest-client#10]
After having checked this repo's README, I don't really see how this package is helping us to build apps calling REST APIs, so I would like to get your input @javorosas to explain me what this package does, and how this package helps developers to call REST APIs? (I want to be sure to not misunderstand what this package does).

In my eyes, as REST defines how REST APIs are working (using resources, HTTP verbs and so on), I was expecting this package to allow me to configure my React component (the inheritance of `RestClient` is perfect) by giving the API base URL, the resource I'd like to consume, and that's it.
_(Of course, with some flexibilities for APIs not following 100% the REST standard)_

An example of what I was expecting :

```javascript
import RestClient from 'react-native-rest-client';

export default class UsersApi extends RestClient {
  constructor () {
    // Initialize with your base URL
    super('https://api.myawesomeservice.com', resource: 'users');
  }
}
```

Then calling it as the following :

```javascript
const usersApi = new UsersApi();

// Get all users (GET '<api base URL>/users')
usersApi.all()
        .then(response => console.log(response.users)) // Array of User objects
        .catch(err => alert(err.message));

// Get user with ID 1 (GET '<api base URL>/users/1')
usersApi.get(1)
        .then(response => console.log(response.user)) // User with ID 1 object
        .catch(err => alert(err.message));

// Creating a new user (POST '<api base URL>/users')
usersApi.create({ name: 'John', ... })
        .then(response => console.log(response.user)) // Created user object
        .catch(err => alert(err.message));

// Updating the user with ID 1 (PUT/PATCH '<api base URL>/users/1')
usersApi.update(1, { name: 'John', ... })
        .then(response => console.log(response.user)) // Updated user object
        .catch(err => alert(err.message));

// Destroying the user with ID 1 (DELETE '<api base URL>/users/1')
usersApi.destroy(1)
        .then(response => console.log(response.user)) // Destroyed user object
        .catch(err => alert(err.message));

// Flexible way of calling (GET '<api base URL>/users/1/unlock')
usersApi.request(RestClient.GET, 1, '/unlock')
        .then(response => console.log(response.body)) // API Response body field
        .catch(err => alert(err.message));
```

Or, regarding the last example calling the user's `unlock`, we could then follow what is already shown in this repo's README, updating the `UsersApi` component :

```javascript
import RestClient from 'react-native-rest-client';

export default class UsersApi extends RestClient {
  constructor () {
    // Initialize with your base URL
    super('https://api.myawesomeservice.com', resource: 'users');
  }

  unlock(id) {
    return this.GET(id, '/unlock');
  }
}
```

With this, it's very easy and fast to build apps consuming REST APIs.

**Comment by zedtux** [comment]
I actually have [forked and implemented a RESTful version of this package](https://gitlab.com/zedtux/react-native-restful-client), so let's close this one.

**Comment by javorosas** [comment]
@zedtux What you propose would indeed create a strict 100% REST client (whatever that means). But in my personal experience, 99% of real world applications don't fit into that model. It would simply become useless for anything that's slightly more complex than a to-do list.

I think it's great you forked it though. Have fun.

**Comment by zedtux** [comment]
Thank you @javorosas for your comment.

Using the `request()` function you can customise your client, so it should be possible to manage custom actions.
Regarding multiple level APIs (/users/1/posts/1/comments), I'm thinking of a way to embed module instances in order to build the final route.

**Comment by javorosas** [comment]
My problem is not "how do you call different actions?", but rather "what am I supposed to do with the actions that were created and have no use?".

Example:

`myApi.balance.get()` | Gets your current balance
`myApi.balance.update()` | Obviously we don't have an endpoint for updating your balance

**Comment by zedtux** [comment]
Well, in my opinion, you are missing a very important point: It isn't the responsibility of the RESTful client to defines if an action can be called or not, but it is the responsibility of the server/backend.

From this point of view, the client allow any kind of actions, and the server reply to them accordingly (200 if is fine, 404/403 when not).

Anyway, now that I built my forked version, I'm trying to convince you about anything, but if you have other questions, please feel free to ask :)
