### ISSUE TITLE
How To Catch Promise

### ISSUE THREAD

**Issue by prakasa1904** [javorosas/react-native-rest-client#2]
Hi, I use your libs, it's so light. But I still have problem to handle error :

Possible Unhandled Promise Rejection, where I should add catch..

**Comment by seclace** [comment]
Hi, @prakasa1904. Promises needs to be catched where you are gets the result of calling method that returns the promise:

    myMethod() {
        return new Promise((resolve, reject) => {
            if (someError) reject();

            ...promise body

            resolve();
        })
    }

anywhere you calls your 'myMethod' you need to add `.catch` with any function-handler you want

    myMethod()
        .then(result => result)
        .catch(error => error);
