### ISSUE TITLE
Ability to return Promise for response before it is json parsed

### ISSUE THREAD

**Issue by jonathanwmaddison** [javorosas/react-native-rest-client#3]
I ran into an issue with react-native-rest-client when receiving a response from an api call that did not include JSON (simply an 202 response). How about adding a non-json response option to the api? It is has been very helpful for a project I'm working on. Thanks for sharing it!

**Comment by mattsains** [comment]
I also needed this feature, so I submitted a pull request: https://github.com/javorosas/react-native-rest-client/pull/5

**Comment by jonathanwmaddison** [comment]
Looks good! Thank you.

**Comment by ProteanDev** [comment]
Hi Guys,
will this setup work for this library?
`headers: { ContentType: 'application/x-www-form-urlencoded', Accept: 'application/json' }`
